
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 * MAKE QUERY A FUCKING PARAMETER
 * @author JoshuaZambales
 */
public class NewJFrame extends javax.swing.JFrame {

   /**
     * Creates new form NewJFrame
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
   public NewJFrame() throws ClassNotFoundException, SQLException {
       initComponents();
       createTables("root", "root"); //replace with your mysql username and password
           
       //DefaultTableModel dtm = execQuer2("root","root", "select * from product_t");
       //EmloyeeTable.setModel(dtm);
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        CreateProject = new javax.swing.JButton();
        LoadProject = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Project2Panel = new javax.swing.JPanel();
        EmployeScroll = new javax.swing.JScrollPane();
        EmloyeeTable1 = new javax.swing.JTable();
        AddEmployee = new javax.swing.JButton();
        RemoveEmployee = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        MaterialScroll = new javax.swing.JTable();
        EmployeeInfoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddSupply = new javax.swing.JButton();
        RemoveSupply = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        EmloyeeTable = new javax.swing.JTable();
        AddEmployee1 = new javax.swing.JButton();
        RemoveEmployee1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddItem1 = new javax.swing.JButton();
        RemoveItem1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateProject.setText("Create Project");

        LoadProject.setText("Load Project");
        LoadProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadProjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadProject)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateProject)
                    .addComponent(LoadProject))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        Project2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Project2Panel.setName(""); // NOI18N

        EmployeScroll.setAutoscrolls(true);
        EmployeScroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        EmloyeeTable1.setAutoCreateRowSorter(true);
        EmloyeeTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        EmployeScroll.setViewportView(EmloyeeTable1);
        if (EmloyeeTable1.getColumnModel().getColumnCount() > 0) {
            EmloyeeTable1.getColumnModel().getColumn(0).setHeaderValue("Name");
            EmloyeeTable1.getColumnModel().getColumn(1).setHeaderValue("Rate");
            EmloyeeTable1.getColumnModel().getColumn(2).setHeaderValue("Working Hours");
            EmloyeeTable1.getColumnModel().getColumn(3).setHeaderValue("Total");
        }

        AddEmployee.setText("Add Employee");

        RemoveEmployee.setText("Remove Employee");

        MaterialScroll.setAutoCreateRowSorter(true);
        MaterialScroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(MaterialScroll);

        EmployeeInfoLabel.setText("Employee Information");

        jLabel4.setText(" Material/Supplies Information");

        AddSupply.setText("Add");
        AddSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSupplyActionPerformed(evt);
            }
        });

        RemoveSupply.setText("Remove");
        RemoveSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveSupplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Project2PanelLayout = new javax.swing.GroupLayout(Project2Panel);
        Project2Panel.setLayout(Project2PanelLayout);
        Project2PanelLayout.setHorizontalGroup(
            Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Project2PanelLayout.createSequentialGroup()
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Project2PanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(EmployeeInfoLabel))
                    .addGroup(Project2PanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                                .addComponent(EmployeScroll))
                            .addComponent(jLabel4)
                            .addGroup(Project2PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Project2PanelLayout.createSequentialGroup()
                                        .addComponent(AddEmployee)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RemoveEmployee))
                                    .addGroup(Project2PanelLayout.createSequentialGroup()
                                        .addComponent(AddSupply)
                                        .addGap(18, 18, 18)
                                        .addComponent(RemoveSupply)))))))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        Project2PanelLayout.setVerticalGroup(
            Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Project2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeeInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployee)
                    .addComponent(RemoveEmployee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddSupply)
                    .addComponent(RemoveSupply))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Project2Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Project2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Project 2", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName(""); // NOI18N

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        EmloyeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Rate", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(EmloyeeTable);

        AddEmployee1.setText("Add Employee");
        AddEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployee1ActionPerformed(evt);
            }
        });

        RemoveEmployee1.setText("Remove Employee");

        ItemTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(ItemTable1);

        jLabel1.setText("Employee Information");

        jLabel2.setText(" Material/Supplies Information");

        AddItem1.setText("Add");
        AddItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItem1ActionPerformed(evt);
            }
        });

        RemoveItem1.setText("Remove");
        RemoveItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItem1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AddEmployee1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RemoveEmployee1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AddItem1)
                                        .addGap(18, 18, 18)
                                        .addComponent(RemoveItem1))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployee1)
                    .addComponent(RemoveEmployee1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItem1)
                    .addComponent(RemoveItem1))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Project 1", jPanel2);

        jTabbedPane2.addTab("Projects", jTabbedPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Project", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jScrollPane7.setViewportView(jScrollPane5);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Employees", jPanel5);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Update Inventory");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton3)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Warehouse", jPanel4);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(393, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Purchase Orders", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        
    
    /**
     * connects to jcarl database, assuming that the database has already been created after createTables() was called
     * @param user - username for mysql
     * @param pass - password for mysql
     * @return Statement (where queries will be executed)
     * @throws SQLException 
     */
    private Statement connect(String user, String pass) throws SQLException {
        
        //establishing connection
        String stringcon = "jdbc:mysql://localhost:3306/jcarl";
        
        //for param user and pass: allow users to input their own username and password of their sql server
        Connection con = DriverManager.getConnection(stringcon,user,pass);
        
        Statement state = con.createStatement();
        return state;
        
    }
    
    /**
     * THIS WILL CREATE THE DATABASE IF DATABASE DOES NOT EXIST YET
     */
    private void createTables(String user, String pass) {
        String quer1 = "CREATE DATABASE IF NOT EXISTS jcarl;";
        String quer2 = "	CREATE TABLE IF NOT EXISTS project(\n" +
               "		project_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
               "		project_name Varchar(60) not null,\n" +
               "		start_date Date not null,\n" +
               "		end_date Date not null,\n" +
               "		client Varchar(50) not null\n" +
               "		);";
        String quer3 = "	CREATE TABLE IF NOT EXISTS payroll(\n" +
"		payroll_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		employee_id Integer(6) not null,\n" +
"		project_id Integer(6) not null,\n" +
"		rate Double(10,2) not null,\n" +
"		working_hours Integer(1) not null,\n" +
"		amount Double(10,2) not null\n" +
                // for some reason the Foreign Key things create an error
//"		Foreign key (employee_id) references employee(employee_id) on delete cascade on update restrict,\n" +
//"		Foreign key (project_id) references project(project_id) on delete cascade on update restrict\n" +
"		);";
        String quer4 = "	CREATE TABLE IF NOT EXISTS employee(\n" +
"		employee_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		employee_name Varchar(60) not null,\n" +
"		rate DOUBLE(10,2) not null\n" +
"		);";
        
        String quer5 = "	CREATE TABLE IF NOT EXISTS purchase_order(\n" +
"		po_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		project_id Integer(6) not null,\n" +
"		date_issued Date not null,\n" +
"		total_price Double(10,2) not null\n" +
//"		Foreign key (project_id) references project(project_id) on delete cascade on update restrict\n" +
"		);";
        String quer6 = "	CREATE TABLE IF NOT EXISTS supplier(\n" +
"		supplier_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		supplier_name Varchar(60) not null,\n" +
"		category Varchar(50) not null\n" +
"		);";
        String quer7 = "	CREATE TABLE IF NOT EXISTS material(\n" +
"		material_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		material_name Varchar(50) not null,\n" +
"		quantity Integer(5) not null,\n" +
"		in_warehouse Boolean not null,\n" +
"		price Double(10,2) not null\n" +
"		);";
           
       try {
           
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/?user="+ user +"&password=" + pass);
           Statement stmt = con.createStatement();
           stmt.executeUpdate(quer1); //creates database
           stmt.close();
           con.close();
           
           //adds tables to database
           execQuer1(user,pass,quer2);
           execQuer1(user,pass,quer3);
           execQuer1(user,pass,quer4);
           execQuer1(user,pass,quer5);
           execQuer1(user,pass,quer6);
           execQuer1(user,pass,quer7);
           
       } catch (SQLException ex) {
           Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
           System.out.print("Wrong username and/or password");
       }
    }
    
    /**
     * For queries that don't have results
     * @param user
     * @param pass
     * @param quer - query string to be executed
     * @throws SQLException 
     */
    private void execQuer1(String user, String pass, String quer) throws SQLException {
        Statement state = connect(user,pass);
        state.executeUpdate(quer);
        state.close();
    }
    
    /**
     * show the results of a query through a table
     * @param user
     * @param pass
     * @param quer - query string to be executed
     * @return the table that will attach to some table in the GUI
     * @throws SQLException
     * @throws InstantiationException
     * @throws ClassNotFoundException
     * @throws IllegalAccessException 
     */
    private DefaultTableModel execQuer2(String user, String pass, String quer) throws SQLException, InstantiationException, ClassNotFoundException, IllegalAccessException {
        Statement state = connect(user,pass);
        ResultSet rs = state.executeQuery(quer);
        DefaultTableModel dtm = getTable(rs); //turn metadata of result into a table
        state.close();
        return dtm; //return the table that will attach to some table in the GUI
    }
    
    /**
     * turns the ResultSet into a table
     * @param rs - ResultSet from the query executed
     * @return meta data turned table
     * @throws SQLException 
     */
    private DefaultTableModel getTable(ResultSet rs) throws SQLException{
        ResultSetMetaData rsmetadata = rs.getMetaData();

        //store no. of columns
        int col = rsmetadata.getColumnCount();

        //This object will pass data into JTable
        DefaultTableModel dtm = new DefaultTableModel();
        Vector columns_name = new Vector();
        Vector data_rows = new Vector();

        for (int i=1; i < col; i++){
            columns_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(columns_name);

        while(rs.next()){
            data_rows = new Vector();
            for(int j=1;j<col;j++){
                data_rows.addElement(rs.getString(j));
            }
            dtm.addRow(data_rows);
        }
        
        return dtm;
        
    }
    
    private void LoadProjectActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:   
    }                                       

    private void RemoveSupplyActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void AddSupplyActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void RemoveItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void AddItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.out.println("Clicked Add Item");
    }                                        

    private void AddEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.out.println("Clicked Add Employee");        // TODO add your handling code here:
    }                                            

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       // JFrame window = new NewJFrame("lol");
        //window.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (        ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton AddEmployee1;
    private javax.swing.JButton AddItem1;
    private javax.swing.JButton AddSupply;
    private javax.swing.JButton CreateProject;
    private javax.swing.JTable EmloyeeTable;
    private javax.swing.JTable EmloyeeTable1;
    private javax.swing.JScrollPane EmployeScroll;
    private javax.swing.JLabel EmployeeInfoLabel;
    private javax.swing.JTable ItemTable1;
    private javax.swing.JButton LoadProject;
    private javax.swing.JTable MaterialScroll;
    private javax.swing.JPanel Project2Panel;
    private javax.swing.JButton RemoveEmployee;
    private javax.swing.JButton RemoveEmployee1;
    private javax.swing.JButton RemoveItem1;
    private javax.swing.JButton RemoveSupply;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration                   
}
