
import com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *MAKE QUERY A FUCKING PARAMETER
 * @author JoshuaZambales
 */
public class NewJFrame extends javax.swing.JFrame {
	private String user, pass, proj1, proj2;
        private boolean tab1, tab2;
   /**
     * Creates new form NewJFrame
     * @throws java.lang.ClassNotFoundException
     */
    public NewJFrame() throws ClassNotFoundException, SQLException {
       initComponents();
//replace with your mysql username and password
       user = "root";
       pass = "root";
       tab1 = false;
       tab2 = false;
       createTables(user, pass); 
       //populate();
           
        try {
            DefaultTableModel dtm3 = execQuer2(user,pass,"select project_name, date_issued, total_price\n" +
            "from project left join purchase_order\n" +
            "on project.project_id = purchase_order.project_id;");
            POTable.setModel(dtm3);
            
            DefaultTableModel dtm4 = execQuer2(user,pass,"select employee.employee_name as EMPLOYEE, GROUP_CONCAT(distinct project.project_name order by project.project_id asc separator ', ') as PROJECT \n" +
            "from employee left join payroll on employee.employee_id = payroll.employee_id\n" +
            "left join project on project.project_id = payroll.project_id\n" +
            "group by employee_name\n" +
            "order by employee.employee_id asc;");
            EmployeesTable.setModel(dtm4);
            
            
        } catch (InstantiationException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
    }
    

     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        CreateProject = new javax.swing.JButton();
        LoadProject = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        Tab1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        Project2Panel = new javax.swing.JPanel();
        EmployeScroll = new javax.swing.JScrollPane();
        PayrollTable1 = new javax.swing.JTable();
        AddEmployee1 = new javax.swing.JButton();
        RemoveEmployee1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        MaterialTable1 = new javax.swing.JTable();
        EmployeeInfoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddMaterial1 = new javax.swing.JButton();
        RemoveMaterial1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        Week1 = new javax.swing.JTextField();
        Week1Button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PayrollTable2 = new javax.swing.JTable();
        AddEmployee2 = new javax.swing.JButton();
        RemoveEmployee2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddItem2 = new javax.swing.JButton();
        RemoveItem2 = new javax.swing.JButton();
        Week2 = new javax.swing.JTextField();
        Week2Button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        AddtoEmployee = new javax.swing.JButton();
        RemoveToEmployee = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        EmployeesTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        WarehouseTable = new javax.swing.JTable();
        UpdateInventory = new javax.swing.JButton();
        AddWarehouse = new javax.swing.JButton();
        RemoveWarehouse = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        POTable = new javax.swing.JTable();
        ADDPO = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateProject.setText("Create Project");
        CreateProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProjectActionPerformed(evt);
            }
        });

        LoadProject.setText("Load Project");
        LoadProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    LoadProjectActionPerformed(evt);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CreateProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoadProject)
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateProject)
                    .addComponent(LoadProject))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Tab1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        Tab1.setToolTipText("");
        Tab1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tab1KeyPressed(evt);
            }
        });

        Project2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Project2Panel.setName(""); // NOI18N

        EmployeScroll.setAutoscrolls(true);
        EmployeScroll.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PayrollTable1.setAutoCreateRowSorter(true);
        PayrollTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        EmployeScroll.setViewportView(PayrollTable1);
        if (PayrollTable1.getColumnModel().getColumnCount() > 0) {
            PayrollTable1.getColumnModel().getColumn(0).setHeaderValue("Name");
            PayrollTable1.getColumnModel().getColumn(1).setHeaderValue("Rate");
            PayrollTable1.getColumnModel().getColumn(2).setHeaderValue("Working Hours");
            PayrollTable1.getColumnModel().getColumn(3).setHeaderValue("Total");
        }

        AddEmployee1.setText("Add Employee");
        AddEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployee1ActionPerformed(evt);
            }
        });

        RemoveEmployee1.setText("Remove Employee");
        RemoveEmployee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployee1ActionPerformed(evt);
            }
        });

        MaterialTable1.setAutoCreateRowSorter(true);
        MaterialTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(MaterialTable1);

        EmployeeInfoLabel.setText("Employee Information");

        jLabel4.setText(" Material/Supplies Information");

        AddMaterial1.setText("Add");
        AddMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    AddMaterial1ActionPerformed(evt);
                } catch (        SQLException | InstantiationException | ClassNotFoundException | IllegalAccessException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        RemoveMaterial1.setText("Remove");
        RemoveMaterial1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveMaterial1ActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField1");

        Week1Button.setText("jButton1");
        Week1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Week1ButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Week:");

        javax.swing.GroupLayout Project2PanelLayout = new javax.swing.GroupLayout(Project2Panel);
        Project2Panel.setLayout(Project2PanelLayout);
        Project2PanelLayout.setHorizontalGroup(
            Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Project2PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(Project2PanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Project2PanelLayout.createSequentialGroup()
                                .addComponent(AddEmployee1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RemoveEmployee1))
                            .addGroup(Project2PanelLayout.createSequentialGroup()
                                .addComponent(AddMaterial1)
                                .addGap(18, 18, 18)
                                .addComponent(RemoveMaterial1))))
                    .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Project2PanelLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(EmployeeInfoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Week1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Week1Button))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                        .addComponent(EmployeScroll, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(323, Short.MAX_VALUE))
            .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Project2PanelLayout.createSequentialGroup()
                    .addGap(364, 364, 364)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(365, Short.MAX_VALUE)))
        );
        Project2PanelLayout.setVerticalGroup(
            Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Project2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeInfoLabel)
                    .addComponent(Week1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Week1Button)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployee1)
                    .addComponent(RemoveEmployee1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddMaterial1)
                    .addComponent(RemoveMaterial1))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(Project2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Project2PanelLayout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Project2Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Project2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        Tab1.addTab("Project 1", jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName(""); // NOI18N

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PayrollTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Rate", "Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(PayrollTable2);

        AddEmployee2.setText("Add Employee");
        AddEmployee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployee2ActionPerformed(evt);
            }
        });

        RemoveEmployee2.setText("Remove Employee");
        RemoveEmployee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployee2ActionPerformed(evt);
            }
        });

        ItemTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(ItemTable2);

        jLabel1.setText("Employee Information");

        jLabel2.setText(" Material/Supplies Information");

        AddItem2.setText("Add");
        AddItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItem2ActionPerformed(evt);
            }
        });

        RemoveItem2.setText("Remove");
        RemoveItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItem2ActionPerformed(evt);
            }
        });

        Week2.setText("      ");

        Week2Button.setText("jButton5");
        Week2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Week2ButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Week:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addGap(156, 156, 156)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Week2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Week2Button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AddEmployee2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RemoveEmployee2))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(AddItem2)
                                        .addGap(18, 18, 18)
                                        .addComponent(RemoveItem2))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Week2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Week2Button)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEmployee2)
                    .addComponent(RemoveEmployee2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddItem2)
                    .addComponent(RemoveItem2))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        Tab1.addTab("Project 2", jPanel2);

        jTabbedPane2.addTab("Projects", Tab1);

        AddtoEmployee.setText("Add Employee");
        AddtoEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoEmployeeActionPerformed(evt);
            }
        });

        RemoveToEmployee.setText("Remove Employee");
        RemoveToEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveToEmployeeActionPerformed(evt);
            }
        });

        EmployeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Project", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(EmployeesTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(AddtoEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RemoveToEmployee))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(AddtoEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveToEmployee))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Employees", jPanel5);

        WarehouseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(WarehouseTable);

        UpdateInventory.setText("Update Inventory");
        UpdateInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInventoryActionPerformed(evt);
            }
        });

        AddWarehouse.setText("Add Item");

        RemoveWarehouse.setText("Remove Item");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveWarehouse)
                    .addComponent(AddWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateInventory))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(AddWarehouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveWarehouse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UpdateInventory))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Warehouse", jPanel4);

        POTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(POTable);

        ADDPO.setText("Add ");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDPO)
                    .addComponent(jButton1))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(ADDPO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Purchase Orders", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                
	
	 /**
     * connects to jcarl database, assuming that the database has already been created after createTables() was called
     * @param user - username for mysql
     * @param pass - password for mysql
     * @return Statement (where queries will be executed)
     * @throws SQLException 
     */
    private Statement connect(String user, String pass) throws SQLException {
        
        //establishing connection
        String stringcon = "jdbc:mysql://localhost:3306/jcarl";
        
        //for param user and pass: allow users to input their own username and passowrd of their sql server
        Connection con = DriverManager.getConnection(stringcon,user,pass);
        
        Statement state = con.createStatement();
        return state;
        
    }
    
    /**
     * THIS WILL CREATE THE DATABASE IF DATABASE DOES NOT EXIST YET
     */
    private void createTables(String user, String pass) {
        String quer1 = "CREATE DATABASE IF NOT EXISTS jcarl;";
        String quer2 = "create table IF NOT EXISTS project(\n" +
"		project_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		project_name Varchar(60) not null,\n" +
"		start_date Date not null,\n" +
"		end_date Date not null,\n" + //this should be default null ?? or kailangan talaga may estimate period for each project
"		client Varchar(50) not null\n" +
"		);";
        String quer3 = "create table IF NOT EXISTS employee(\n" +
"		employee_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		employee_name Varchar(60) not null,\n" +
"		rate DOUBLE(10,2) not null\n" +
"		);";
        String quer4 = "create table IF NOT EXISTS purchase_order(\n" +
"		po_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		project_id Integer(6) not null,\n" +
"		date_issued Date not null,\n" +
"		total_price Double(10,2) not null,\n" +
"		Foreign key (project_id) references project(project_id) on delete cascade on update restrict\n" +
"		);";
        
        String quer5 = "create table IF NOT EXISTS supplier(\n" +
"		supplier_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		supplier_name Varchar(60) not null,\n" +
"		category Varchar(50) not null\n" +
"		);";
        String quer6 = "create table IF NOT EXISTS material(\n" +
"		material_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		supplier_id Integer(6) not null,\n" +
"		material_name Varchar(50) not null,\n" +
"		quantity Integer(5) not null,\n" +
"		in_warehouse Boolean not null,\n" +
"		price Double(10,2) not null,\n" +
"		foreign key (supplier_id) references supplier(supplier_id) on delete cascade on update restrict\n" +
"		);";
        String quer7 = "create table IF NOT EXISTS payroll(\n" +
"		payroll_id Integer(6) primary key not null AUTO_INCREMENT,\n" +
"		employee_id Integer(6) not null,\n" +
"		project_id Integer(6) not null,\n" +
"		mon Integer(2),\n" +
"		tues Integer(2),\n" +
"		wed Integer(2),\n" +
"		thurs Integer(2),\n" +
"		fri Integer(2),\n" + 
"		sat Integer(2),\n" +
"		sun Integer(2)," +
"		Foreign key (employee_id) references employee(employee_id) on delete cascade on update restrict,\n" +
"		Foreign key (project_id) references project(project_id) on delete cascade on update restrict\n" +
"		);";
           
       try {
           
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/?user="+ user +"&password=" + pass);
           Statement stmt = con.createStatement();
           stmt.executeUpdate(quer1); //creates database
           stmt.close();
           con.close();
           
           //adds tables to database
           execQuer1(user,pass,quer2);
           execQuer1(user,pass,quer3);
           execQuer1(user,pass,quer4);
           execQuer1(user,pass,quer5);
           execQuer1(user,pass,quer6);
           execQuer1(user,pass,quer7);
           
       } catch (SQLException ex) {
           Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
           System.out.print("Wrong username and/or password");
       }
    }
    
    /**
     * For queries that don't have results
     * @param user
     * @param pass
     * @param quer - query string to be executed
     * @throws SQLException 
     */
    private void execQuer1(String user, String pass, String quer) throws SQLException {
        Statement state = connect(user,pass);
        state.executeUpdate(quer);
        state.close();
    }
    
    /**
     * show the results of a query through a table
     * @param user
     * @param pass
     * @param quer - query string to be executed
     * @return the table that will attach to some table in the GUI
     * @throws SQLException
     * @throws InstantiationException
     * @throws ClassNotFoundException
     * @throws IllegalAccessException 
     */
    private DefaultTableModel execQuer2(String user, String pass, String quer) throws SQLException, InstantiationException, ClassNotFoundException, IllegalAccessException {
        Statement state = connect(user,pass);
        ResultSet rs = state.executeQuery(quer);
        DefaultTableModel dtm = getTable(rs); //turn metadata of result into a table
        state.close();
        return dtm; //return the table that will attach to some table in the GUI
    }
    
    /**
     * turns the ResultSet into a table
     * @param rs - ResultSet from the query executed
     * @return meta data turned table
     * @throws SQLException 
     */
    private DefaultTableModel getTable(ResultSet rs) throws SQLException{
        ResultSetMetaData rsmetadata = rs.getMetaData();

        //store no. of columns
        int col = rsmetadata.getColumnCount();

        //This object will pass data into JTable
        DefaultTableModel dtm = new DefaultTableModel();
        Vector columns_name = new Vector();
        Vector data_rows = new Vector();

        for (int i=1; i < col+1; i++){
            columns_name.addElement(rsmetadata.getColumnName(i));
        }
        dtm.setColumnIdentifiers(columns_name);

        while(rs.next()){
            data_rows = new Vector();
            for(int j=1; j<col+1 ;j++){
                data_rows.addElement(rs.getString(j));
            }
            dtm.addRow(data_rows);
        }
        
        return dtm;
        
    }
    
    /**
     * populate tables with fake info
     */
    private void populate() throws SQLException {
        String quer1 = "insert into project(project_name, start_date, end_date, client) values\n" +
            "(\"JM's New Dorm\", \"2011-01-01\", \"2012-01-01\", \"Captain Board Shorts\"),\n" +
            "(\"Pia's New Dancing Place Whatever\", \"2014-08-09\", \"2015-02-14\", \"Captain Board Shorts\"),\n" +
            "(\"Javy's Old Drum Place Thingy\", \"2008-01-05\",\" 2010-12-12\", \"Lolo mo\"),\n" +
            "(\"Pet House\", \"2013-12-01\", \"2014-12-01\", \"Captain Board Shorts\"),"
                + "(\"McDo Caribbean\", \"2014-10-11\", \"2014-10-15\", \"McDo\"),\n" +
            "(\"Araneta Park\", \"2013-12-12\", \"2014-04-14\", \"Smart\"),\n" +
            "(\"London Bridge in Paranaque\", \"2012-12-21\", \"2013-12-21\", \"Annabelle\");";
        execQuer1(user,pass,quer1);
        
        String quer2 = "insert into employee(employee_name, rate) values\n" +
            "(\"Mang Jose\", 1.00),\n" +
            "(\"Don Romantiko\", 5000.00),\n" +
            "(\"Hari ng Sablay\", 3000.00),\n" +
            "(\"Marco Francisco DeMargue\", 200.00),\n" +
            "(\"FishNChips\", 100.00),"
            + "(\"Michael Jordan\", 1005.00),\n" +
            "(\"George Washing\", 600.50);";
        execQuer1(user,pass,quer2);
        
        String quer3 = "insert into supplier(supplier_name, category) values\n" +
            "(\"Captain Board Shorts' Supplies!\", \"Board Shorts Stuff\"),\n" +
            "(\"Gamit ng Lolo mo\", \"Things\"),\n" +
            "(\"McAfee's Metal Materials\", \"Metal\"),\n" +
            "(\"Lolo's Pake\", \"Pake\"),\n" +
            "(\"Karinderya\", \"Food Stuff\");";
        execQuer1(user,pass,quer3);
        
        String quer4 = "insert into payroll(employee_id, project_id) VALUES\n" +
            "((SELECT employee_id from employee where employee_id=1), (SELECT project_id from project where project_id=1) ),\n" +
            "((SELECT employee_id from employee where employee_id=2), (SELECT project_id from project where project_id=2) ),\n" +
            "((SELECT employee_id from employee where employee_id=3), (SELECT project_id from project where project_id=3) ),\n" + 
            "((SELECT employee_id from employee where employee_id=4), (SELECT project_id from project where project_id=4) ),\n" +
            "((SELECT employee_id from employee where employee_id=5), (SELECT project_id from project where project_id=4) ),\n" +
            "((SELECT employee_id from employee where employee_id=5), (SELECT project_id from project where project_id=1) ),\n" +
            "((SELECT employee_id from employee where employee_id=6), (SELECT project_id from project where project_id=5) ),\n" +
            "((SELECT employee_id from employee where employee_id=7), (SELECT project_id from project where project_id=7) ),\n" +
            "((SELECT employee_id from employee where employee_id=1), (SELECT project_id from project where project_id=6) );";
        execQuer1(user,pass,quer4);
        
        execQuer1(user,pass,"ALTER TABLE material AUTO_INCREMENT = 002000;");
        String quer5 = "insert into material(supplier_id, material_name, quantity, in_warehouse, price) values\n" +
            "(1,\"Board Shorts\", 50, True, 100000.00),\n" +
            "(2,\"Antique Glass\", 20, True, 5000.00),\n" +
            "(3,\"Metal Plastic Bag\", 30, True, 20.00),\n" +
            "(4,\"Pake\", 0, False, 0.99),\n" +
            "(5,\"Fish Bones\",10, True, 15.00),\n" +
            "(5, \"Chicarong Bakal\", 50, True, 55.99),\n" +
            "(1, \"Trunks\", 20, True, 500.00);";
        execQuer1(user,pass,quer5);
        
        String quer6 = "insert into purchase_order(date_issued, total_price, project_id) VALUES\n" +
            "(\"2011-01-01\", 60000.50, (SELECT project_id from project where project_id=1) ),\n" +
            "(\"2014-05-21\", 50000.00, (SELECT project_id from project where project_id=2) ),\n" +
            "(\"2008-01-06\", 10.00, (SELECT project_id from project where project_id=3) ),\n" +
            "(\"2013-12-02\", 600.00, (SELECT project_id from project where project_id=4) ),\n" +
            "(\"2013-12-20\", 500000.00, (SELECT project_id from project where project_id=5) );";
        execQuer1(user,pass,quer6);
    }
    
    private void initTab1(String proj) throws SQLException, InstantiationException, ClassNotFoundException, IllegalAccessException {
        Tab1.setTitleAt(0, proj);
        
        Statement stm = connect(user,pass);
        ResultSet rs = stm.executeQuery("select project_id from project where project_name=\""+proj+"\"");
        rs.next();
        int projid = rs.getInt(1);
        //System.out.println(projid);
        
        /*
        DefaultTableModel dtm = execQuer2(user,pass, "select employee_name, rate, mon, tues, wed, thurs, fri,\n" +
        "SUM(mon+tues+wed+thurs+fri) as 'Total Hours'\n" +
        "from payroll left join employee\n" +
        "on employee.employee_id = payroll.employee_id\n" +
        "where payroll.project_id="+projid+"\n" +
        "group by employee.employee_id;");
        PayrollTable1.setModel(dtm);
        */
        DefaultTableModel dtm = execQuer2(user,pass, "select employee_name, rate,\n" +
        "ifnull(mon, 8) as MONDAY, \n" +
        "ifnull(tues, 8) as TUESDAY, \n" +
        "ifnull(wed,8) as WEDNESDAY, \n" +
        "ifnull(thurs,8) as THURSDAY, \n" +
        "ifnull(fri,7) as FRIDAY,\n" +
        "ifnull(sat,7) as SATURDAY,\n" +
        "ifnull(sun,7) as SUNDAY,\n" +
        "ifnull((sum(mon+tues+wed+thurs+fri)*rate),8*rate) as 'Total Hours'\n" +
        "from payroll left join employee\n" +
        "on employee.employee_id = payroll.employee_id\n" +
        "where payroll.project_id="+projid+"\n" +
        "group by employee.employee_id;");
        PayrollTable1.setModel(dtm);

        DefaultTableModel dtm2 = execQuer2(user,pass,"select material_name, quantity,\n"+
        "case when in_warehouse=1 then 'Yes' else 'No' \n" +
        "end as 'In Warehouse?'\n " +
        "from material;");
        MaterialTable1.setModel(dtm2);
    }
    
    private void initTab2(String proj) throws SQLException, InstantiationException, ClassNotFoundException, IllegalAccessException {
        Tab1.setTitleAt(1, proj);
        
        Statement stm = connect(user,pass);
        ResultSet rs = stm.executeQuery("select project_id from project where project_name=\""+proj+"\"");
        rs.next();
        int projid = rs.getInt(1);
        
        DefaultTableModel dtm = execQuer2(user,pass, "select employee_name, rate,\n" +
        "ifnull(mon, 8) as MONDAY, \n" +
        "ifnull(tues, 8) as TUESDAY, \n" +
        "ifnull(wed,8) as WEDNESDAY, \n" +
        "ifnull(thurs,8) as THURSDAY, \n" +
        "ifnull(fri,7) as FRIDAY,\n" +
        "ifnull(sat,7) as SATURDAY,\n" +
        "ifnull(sun,7) as SUNDAY,\n" +
        "ifnull((sum(mon+tues+wed+thurs+fri)*rate),8*rate) as 'Total Hours'\n" +
        "from payroll left join employee\n" +
        "on employee.employee_id = payroll.employee_id\n" +
        "where payroll.project_id="+projid+"\n" +
        "group by employee.employee_id;");
        PayrollTable2.setModel(dtm);

        DefaultTableModel dtm2 = execQuer2(user,pass,"select material_name, quantity,\n"+
        "case when in_warehouse=1 then 'Yes' else 'No' \n" +
        "end as 'In Warehouse?'\n " +
        "from material;");
        ItemTable2.setModel(dtm2);
    }

  private void LoadProjectActionPerformed(java.awt.event.ActionEvent evt) throws SQLException { 
      Statement stm = connect(user,pass);
      ResultSet rs = stm.executeQuery("select project_name from project;");
      
      ArrayList<String> projlist = new ArrayList<>();
      while(rs.next()) {
          projlist.add(rs.getString(1));
      }
      String[] projl = new String[projlist.size()];
      projlist.toArray(projl);
      
      final JComboBox<String> projl1 = new JComboBox<>(projl);
      final JComboBox<String> projl2 = new JComboBox<>(projl);
      
      Object[] fields = {
            "First Project: ", projl1,
            "Second Project", projl2,
        };
      Object[] options = {"Ok", "Cancel"};
        
      int n = JOptionPane.showOptionDialog(null, fields, 
              "Load Projects", JOptionPane.YES_NO_OPTION, 
              JOptionPane.PLAIN_MESSAGE, null, options, options[1]);
      
      if (n == JOptionPane.OK_OPTION){
          proj1 = (String) projl1.getSelectedItem();
          proj2 = (String) projl2.getSelectedItem();

          tab1 = true;
          tab2 = true;
          
            try {
                initTab1(proj1);
                initTab2(proj2);
            } catch (    InstantiationException | ClassNotFoundException | IllegalAccessException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
      
    }                                           

    private void Tab1KeyPressed(java.awt.event.KeyEvent evt) {                                
        // TODO add your handling code here:   
    }                               

    private void RemoveMaterial1ActionPerformed(java.awt.event.ActionEvent evt) {
        //remove material button in tab/project 1
        System.out.println("in 1");
    }                                               

    private void AddMaterial1ActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, InstantiationException, ClassNotFoundException, IllegalAccessException {                                             
        //tab or project 1
        JTextField m_name = new JTextField();
        JTextField qty = new JTextField();
        JTextField cost = new JTextField();
        JTextField i_ware = new JTextField();
        
        //fix the fields that need to be in the pop-up window
        Object[] fields = {
            "Material Name", m_name,
            "Quantity", qty,
            "Price", cost,
            "In warehouse?", i_ware,
        };
        
        Object[] options = {"Ok", "Cancel"};
        
        int n = JOptionPane.showOptionDialog(null, fields, "Add Material", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        
        try{
            if (n == JOptionPane.OK_OPTION){
                String materialName = m_name.getText();
                String quantity = qty.getText();
                String price = cost.getText();
                String warehouse = i_ware.getText();

                String query = "insert into material(supplier_id, material_name, quantity, in_warehouse, price) values \n" +  "(2, \"" + materialName + "\", " + quantity + ", True," + price + ");";
                execQuer1(user, pass, query);

                JOptionPane.showMessageDialog( null, "New item in inventory: " +  quantity + " " + materialName + " costing " + price + ".", "Your Results", JOptionPane.PLAIN_MESSAGE); 
            }
            //REFRESHING THE GUI
            DefaultTableModel dtm2 = execQuer2(user,pass,"select material_name as 'Material', quantity as 'Quantity', \n" +
                    "case when in_warehouse=1 then 'Yes' else 'No'\n" +
                    "end as 'In Warehouse?'\n" +
                    "from material;");
            MaterialTable1.setModel(dtm2);
        } catch (MySQLSyntaxErrorException lel){
            JOptionPane.showMessageDialog(null, "Please check your entries again.", "Error!", JOptionPane.ERROR_MESSAGE);
        }   catch (  SQLException | InstantiationException | ClassNotFoundException | IllegalAccessException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }    
        
        
    }                                            

    private void RemoveItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // tab or project 2
        System.out.println("in 2");
    }                                           

    private void AddItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.out.println("in 2");
        JTextField m_name = new JTextField();
        JTextField qty = new JTextField();
        JTextField cost = new JTextField();
        JTextField i_ware = new JTextField();
        
        //fix the fields that need to be in the pop-up window
        Object[] fields = {
            "Material Name", m_name,
            "Quantity", qty,
            "Price", cost,
            "In warehouse?", i_ware,
        };
        
        Object[] options = {"Ok", "Cancel"};
        
        int n = JOptionPane.showOptionDialog(null, fields, "Add Material", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);
        
        try{
            if (n == JOptionPane.OK_OPTION){
                String materialName = m_name.getText();
                String quantity = qty.getText();
                String price = cost.getText();
                String warehouse = i_ware.getText();

                String query = "insert into material(supplier_id, material_name, quantity, in_warehouse, price) values \n" +  "(2, \"" + materialName + "\", " + quantity + ", True," + price + ");";
                execQuer1(user, pass, query);

                JOptionPane.showMessageDialog( null, "New item in inventory: " +  quantity + " " + materialName + " costing " + price + ".", "Your Results", JOptionPane.PLAIN_MESSAGE); 
            }
            //REFRESHING THE GUI
            DefaultTableModel dtm2 = execQuer2(user,pass,"select material_name as 'Material', quantity as 'Quantity', \n" +
                    "case when in_warehouse=1 then 'Yes' else 'No'\n" +
                    "end as 'In Warehouse?'\n" +
                    "from material;");
            ItemTable2.setModel(dtm2);
        } catch (MySQLSyntaxErrorException lel){
            JOptionPane.showMessageDialog(null, "Please check your entries again.", "Error!", JOptionPane.ERROR_MESSAGE);
        }   catch (  SQLException | InstantiationException | ClassNotFoundException | IllegalAccessException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }                                        

    private void AddEmployee2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.out.println("in 2");        // TODO add your handling code here:
        //this is the Add Employee button of Project 2 tab
    }                                            

    private void RemoveEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Project 1
        System.out.println("in 1");
    }                                               

    private void AddtoEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        // this is the Add Employee button in the Employees tab
        System.out.println("hire employee!");
    }                                             

    private void RemoveToEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // Employees Tab
        System.out.println("pink slip");
    }                                                

    private void UpdateInventoryActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void Week1ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void Week2ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void RemoveEmployee2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        //project 2 tab
        System.out.println("in 2");
    }                                               

    private void AddEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        //this is the Add Employee button in Project1 tab
        System.out.println("in 1");
    }                                            

    private void CreateProjectActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       // JFrame window = new NewJFrame("lol");
        //window.setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    try {
                        new NewJFrame().setVisible(true);
                    } catch (SQLException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ADDPO;
    private javax.swing.JButton AddEmployee1;
    private javax.swing.JButton AddEmployee2;
    private javax.swing.JButton AddItem2;
    private javax.swing.JButton AddMaterial1;
    private javax.swing.JButton AddWarehouse;
    private javax.swing.JButton AddtoEmployee;
    private javax.swing.JButton CreateProject;
    private javax.swing.JScrollPane EmployeScroll;
    private javax.swing.JLabel EmployeeInfoLabel;
    private javax.swing.JTable EmployeesTable;
    private javax.swing.JTable ItemTable2;
    private javax.swing.JButton LoadProject;
    private javax.swing.JTable MaterialTable1;
    private javax.swing.JTable POTable;
    private javax.swing.JTable PayrollTable1;
    private javax.swing.JTable PayrollTable2;
    private javax.swing.JPanel Project2Panel;
    private javax.swing.JButton RemoveEmployee1;
    private javax.swing.JButton RemoveEmployee2;
    private javax.swing.JButton RemoveItem2;
    private javax.swing.JButton RemoveMaterial1;
    private javax.swing.JButton RemoveToEmployee;
    private javax.swing.JButton RemoveWarehouse;
    private javax.swing.JTabbedPane Tab1;
    private javax.swing.JButton UpdateInventory;
    private javax.swing.JTable WarehouseTable;
    private javax.swing.JTextField Week1;
    private javax.swing.JButton Week1Button;
    private javax.swing.JTextField Week2;
    private javax.swing.JButton Week2Button;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}
